export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const SET_NEW_EVENTS = 'SET_NEW_EVENTS';

export const SELECT_ATTENDEE = 'SELECT_ATTENDEE';
export const SAVE_NEW_ATTENDEE = 'SAVE_NEW_ATTENDEE';
export const UPDATE_ATTENDEES = 'UPDATE_ATTENDEES';
export const SELECT_SELECTED_ATTENDEE_ID = 'SELECT_SELECTED_ATTENDEE_ID';

export const SELECT_EVENT = 'SELECT_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';

export const FIREBASE_REF_SET = 'FIREBASE_REF_SET'