export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const FAILED_TO_CREATE_NEW_USER = 'FAILED_TO_CREATE_NEW_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const FAILED_TO_LOGIN = 'FAILED_TO_LOGIN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';
export const SET_RECRUITER_INFO = 'SET_RECRUITER_INFO';

export const PROFILE_PICTURE_DOWNLOADED = 'PROFILE_PICTURE_DOWNLOADED';
export const RESUME_DOWNLOADED = 'RESUME_DOWNLOADED';
export const SELECT_ATTENDEE = 'SELECT_ATTENDEE';
export const SAVE_NEW_ATTENDEE = 'SAVE_NEW_ATTENDEE';
export const UPDATE_ATTENDEES = 'UPDATE_ATTENDEES';
export const SELECT_SELECTED_ATTENDEE_ID = 'SELECT_SELECTED_ATTENDEE_ID';


export const READY_TO_EMAIL_RESUMES = 'READY_TO_EMAIL_RESUME';
export const SELECT_EVENT = 'SELECT_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';
export const REMOVE_DOWNLOADED_RESUME = 'REMOVE_DOWNLOADED_RESUME';
export const SET_NEW_EVENTS = 'SET_NEW_EVENTS';


export const FIREBASE_REF_SET = 'FIREBASE_REF_SET'